// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package database

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Endpoint struct {
	ID             pgtype.UUID
	OrganizationID pgtype.UUID
	SystemName     string
	PublicKey      string
	ConnectedOn    pgtype.Timestamp
	ApprovedOn     pgtype.Timestamp
	LastSeen       pgtype.Timestamp
	Enabled        bool
}

type EndpointGroupAssignment struct {
	EndpointID     pgtype.UUID
	GroupID        pgtype.UUID
	OrganizationID pgtype.UUID
}

type EndpointScheduleAssignment struct {
	EndpointID     pgtype.UUID
	ScheduleID     int32
	OrganizationID pgtype.UUID
}

type Group struct {
	ID             pgtype.UUID
	OrganizationID pgtype.UUID
	Name           string
}

type GroupScheduleAssignment struct {
	GroupID        pgtype.UUID
	ScheduleID     int32
	OrganizationID pgtype.UUID
}

type Job struct {
	ID             int64
	EndpointID     pgtype.UUID
	GroupID        pgtype.UUID
	OrganizationID pgtype.UUID
	Type           int32
	Params         []byte
	Created        pgtype.Timestamp
	Completed      pgtype.Timestamp
	Status         pgtype.Int4
	Output         pgtype.Text
}

type Organization struct {
	ID   pgtype.UUID
	Name string
}

type Schedule struct {
	ID             int32
	Name           string
	OrganizationID pgtype.UUID
	Days           string
	StartTime      pgtype.Time
	FinishTime     pgtype.Time
}
