// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package database

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Group struct {
	ID             pgtype.UUID
	OrganizationID pgtype.UUID
	Name           string
}

type GroupScheduleAssignment struct {
	GroupID        pgtype.UUID
	ScheduleID     int32
	OrganizationID pgtype.UUID
}

type Node struct {
	ID              pgtype.UUID
	OrganizationID  pgtype.UUID
	PublicKey       string
	Label           pgtype.Text
	Hostname        string
	ClientVersion   string
	PendingSources  bool
	PendingSchedule bool
	OsKernel        string
	OsName          string
	OsMajor         int32
	OsMinor         int32
	OsBuild         int32
	ConnectedOn     pgtype.Timestamp
	ApprovedOn      pgtype.Timestamp
	LastSeen        pgtype.Timestamp
	Approved        bool
}

type NodeGroupAssignment struct {
	NodeID         pgtype.UUID
	GroupID        pgtype.UUID
	OrganizationID pgtype.UUID
}

type NodeScheduleAssignment struct {
	NodeID         pgtype.UUID
	ScheduleID     int32
	OrganizationID pgtype.UUID
}

type Organization struct {
	ID   pgtype.UUID
	Name string
}

type PackageJob struct {
	ID               int64
	NodeID           pgtype.UUID
	GroupID          pgtype.UUID
	OrganizationID   pgtype.UUID
	Action           int32
	Name             string
	Version          pgtype.Text
	IgnoreChecksum   bool
	InstallOnUpgrade bool
	Force            bool
	VerboseOutput    bool
	NotSilent        bool
	CreatedAt        pgtype.Timestamp
	CompletedAt      pgtype.Timestamp
	Status           pgtype.Int4
	Output           pgtype.Text
}

type Schedule struct {
	ID             int32
	Name           string
	OrganizationID pgtype.UUID
	Days           string
	StartTime      pgtype.Time
	FinishTime     pgtype.Time
}

type ScheduleJob struct {
	ID             int64
	NodeID         pgtype.UUID
	GroupID        pgtype.UUID
	OrganizationID pgtype.UUID
	CreatedAt      pgtype.Timestamp
	CompletedAt    pgtype.Timestamp
}
