// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0
// source: schedule.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getEndpointSchedules = `-- name: GetEndpointSchedules :many
WITH endpoint_schedules AS (
    SELECT 
        es.schedule_id,
        s.name,
        s.days,
        s.start_time,
        s.finish_time
    FROM 
        endpoint_schedule_assignments es
    JOIN 
        schedules s ON es.schedule_id = s.id
    WHERE 
        es.endpoint_id = $1
), group_schedules AS (
    SELECT 
        gs.schedule_id,
        s.name,
        s.days,
        s.start_time,
        s.finish_time
    FROM 
        endpoint_group_assignments ega
    JOIN 
        group_schedule_assignments gs ON ega.group_id = gs.group_id
    JOIN 
        schedules s ON gs.schedule_id = s.id
    WHERE 
        ega.endpoint_id = $1
)
SELECT DISTINCT
    schedule_id,
    name,
    days,
    start_time,
    finish_time
FROM 
    endpoint_schedules
UNION
SELECT DISTINCT
    schedule_id,
    name,
    days,
    start_time,
    finish_time
FROM 
    group_schedules
`

type GetEndpointSchedulesRow struct {
	ScheduleID int32
	Name       string
	Days       string
	StartTime  pgtype.Time
	FinishTime pgtype.Time
}

// Get a list of all schedules that apply to an endpoint
func (q *Queries) GetEndpointSchedules(ctx context.Context, endpointID pgtype.UUID) ([]GetEndpointSchedulesRow, error) {
	rows, err := q.db.Query(ctx, getEndpointSchedules, endpointID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetEndpointSchedulesRow
	for rows.Next() {
		var i GetEndpointSchedulesRow
		if err := rows.Scan(
			&i.ScheduleID,
			&i.Name,
			&i.Days,
			&i.StartTime,
			&i.FinishTime,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
